---
- hosts: localhost
  tasks:
    - name: Ensure APT is up-to-date
      become: yes
      apt:
        update_cache: yes

    - name: Copy configuration files and installers
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: './config/', dest: '/tmp/config/' }
        - { src: './installers/', dest: '/tmp/installers/' }
        - { src: './dotfiles', dest: '{{ ansible_env.HOME }}/' }

    - name: Install updates
      become: yes
      command:
        cmd: "bash {{ item }}"
      with_items:
        - /tmp/installers/install-updates.sh

    - name: Run installers
      command:
        cmd: "bash {{ item }}"
      with_items:
        - /tmp/installers/install-dotfiles.sh
        - /tmp/installers/install-shell.sh
        - /tmp/installers/install-grc.sh
        - /tmp/installers/install-go.sh
        - /tmp/installers/install-pipx.sh
        - /tmp/installers/install-vim.sh
        - /tmp/installers/install-tools.sh
        - /tmp/installers/install-wordlists.sh

    - name: Clean up APT and tmp
      become: yes
      file:
        path: "{{ item }}"
        state: absent
      loop:
          - /var/lib/apt/lists/*
          - /tmp/*

    - name: Copy conf.curl to /usr/share/grc/
      become: yes
      copy:
        src: './config/conf.curl'
        dest: '/usr/share/grc/conf.curl'

    - name: Copy nginx.conf to /etc/nginx/
      become: yes
      copy:
        src: './config/nginx.conf'
        dest: '/etc/nginx/conf.curl'

    - name: Copy wordlists to /usr/share/wordlists/
      become: yes
      copy:
        src: './config/wordlists'
        dest: '/usr/share/wordlists'
    - name: Copy nuclei configuration files to /usr/share/nuclei-configs/
      become: yes
      copy:
        src: './config/nuclei-templates'
        dest: '/usr/share/nuclei-templates'
    - name: Copy coc configuration to ~/.vim/
      become: yes
      copy:
        src: './config/coc-config.json'
        dest: '~/.vim/'
