---
- name: Run installers
  command:
    cmd: "bash {{ item }}"
  with_items:
      - /root/installers/install-dotfiles.sh
      - /root/installers/install-shell.sh
        #      - /root/installers/install-go.sh
        # - /root/installers/install-vim.sh

      # Add other default installs here if wanted

- name: Clean up APT and tmp
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  loop:
      - /var/lib/apt/lists/*
      - /tmp/*
