---
- name: Run installers
  command:
    cmd: "bash {{ item }}"
  with_items:
      - /root/installers/install-dotfiles.sh
      - /root/installers/install-shell.sh
      - /root/installers/install-go.sh
      - /root/installers/install-vim.sh
    # - /root/installers/install-tools.sh
    # - /root/installers/install-wordlists.sh
    # - /root/installers/install-msf.sh

- name: Clean up APT and tmp
  become: yes
  file:
    path: "{{ item }}"
    state: absent
  loop:
      - /var/lib/apt/lists/*
      - /tmp/*
